travis:
  secure:
    BINSTAR_TOKEN: Cu4KxZLrGETDKDCdY8NE7pf15YQ07bRRMZKfyhEWwmT20qBU57bBZ7h/vh6qn+r9816Cst/l2FrCpdYKAEtuFjR/+lwqatYQixSVKZlHN1ELgybot5csRDJDSut3FekT700cvHg4PINDki9ItoKLWhZODtZI1VXWbWXMF+RYwQJiPAx9g6lp+bNuq4SLnmNy/grfz1JvmuO7OnoQvviVkiybfSzyYnGc7Hyme9k6aVNKmWDvJRRFB9WYjYSh/SnYnVL7qGUrUAVQfvJPuIzSHGw7/gwgBD3UELSUMRDhwfOF8O3RpiHRNJ+rDoiCi+hYkSq+igHFDR6zA79TPU6dubCIAZ+wgq26n7OfhqjeRrQzyYPexYfmWx2H3zw5EOSfP3vmQA+NY72Ss8wn7vs3K/usNwUdOycdVRD3VUG3W5Y4eJ/NlFMRKZpHK01ABcElQzZO34WpUg7obbaRsg7vPdOZn6SY/EnKfDawbilE7v31Y6l3mG9j2sip/pBeOuUlrV3V3WBcp+9DNhDwjLYg6qHOXkyLQ+JRrI92qJWFYTjLrveOW+wqk8OMZ3DnzivByr5ATVuGnA+Qv/5CVUU7bscBRkWzD8GODG3IE40nZjm8gfQVqynmXcF8aXGc9/614SHyIAu8XJHPVKS4c+xHJY0ABWr7tFdH4atnUm0fbeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
